"""AP4.5 add confidence transparency fields to proposals

Revision ID: 1aeb3778e9cb
Revises: ebda716a41f7
Create Date: 2026-07-11 23:47:16.206778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aeb3778e9cb'
down_revision: Union[str, Sequence[str], None] = 'ebda716a41f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('value_grounded', sa.Float(), nullable=True))
    op.add_column('proposals', sa.Column('value_grounded_reason', sa.Text(), nullable=True))
    op.add_column('proposals', sa.Column('confidence_rationale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'confidence_rationale')
    op.drop_column('proposals', 'value_grounded_reason')
    op.drop_column('proposals', 'value_grounded')
    # ### end Alembic commands ###
