"""AP4.1 add AP3.5 guard fields to proposals

Revision ID: ebda716a41f7
Revises: 55f1c1b3903a
Create Date: 2026-07-11 10:54:29.202439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebda716a41f7'
down_revision: Union[str, Sequence[str], None] = '55f1c1b3903a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('correction_kind', sa.String(length=40), nullable=True))
    op.add_column('proposals', sa.Column('target_entity_type', sa.String(length=100), nullable=True))
    op.add_column('proposals', sa.Column('target_entity_id', sa.String(length=255), nullable=True))
    op.add_column('proposals', sa.Column('identity_check_supported', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'identity_check_supported')
    op.drop_column('proposals', 'target_entity_id')
    op.drop_column('proposals', 'target_entity_type')
    op.drop_column('proposals', 'correction_kind')
    # ### end Alembic commands ###
