"""AP7.2 add memory_support, memory_support_reason, formula_version to proposals

Revision ID: 2f47c4554ece
Revises: 7c4e2d9a8f10
Create Date: 2026-07-12 16:22:49.142308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f47c4554ece'
down_revision: Union[str, Sequence[str], None] = '7c4e2d9a8f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('memory_support', sa.Float(), nullable=True))
    op.add_column('proposals', sa.Column('memory_support_reason', sa.Text(), nullable=True))
    op.add_column('proposals', sa.Column('formula_version', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'formula_version')
    op.drop_column('proposals', 'memory_support_reason')
    op.drop_column('proposals', 'memory_support')
    # ### end Alembic commands ###
