"""AP2 initial schema

Revision ID: 55f1c1b3903a
Revises: 
Create Date: 2026-07-08 17:07:13.182239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f1c1b3903a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=True),
    sa.Column('user_ref', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots_meta',
    sa.Column('snapshot_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('errors_before', sa.Integer(), nullable=True),
    sa.Column('warnings_before', sa.Integer(), nullable=True),
    sa.Column('errors_after', sa.Integer(), nullable=True),
    sa.Column('warnings_after', sa.Integer(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('tokens_completion', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('proposals',
    sa.Column('proposal_id', sa.String(length=255), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('affected_entity', sa.String(length=255), nullable=True),
    sa.Column('target_path', sa.String(length=500), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('suggested_value', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('schema_valid', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots_meta.snapshot_id'], ),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    op.create_index(op.f('ix_proposals_snapshot_id'), 'proposals', ['snapshot_id'], unique=False)
    op.create_table('memory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('affected_entity_pattern', sa.String(length=255), nullable=True),
    sa.Column('suggested_value', sa.JSON(), nullable=True),
    sa.Column('final_value', sa.JSON(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('revalidation_ok', sa.Boolean(), nullable=True),
    sa.Column('source_proposal_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_proposal_id'], ['proposals.proposal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('final_value', sa.JSON(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewer_ref', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revalidation_result', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.proposal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_proposal_id'), 'reviews', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_proposal_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('memory_items')
    op.drop_index(op.f('ix_proposals_snapshot_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('snapshots_meta')
    op.drop_table('sessions')
    # ### end Alembic commands ###
