"""AP7 add affected_entity_id to memory_items

Revision ID: 57dbefe2d996
Revises: 2f47c4554ece
Create Date: 2026-07-31 19:26:42.175669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57dbefe2d996'
down_revision: Union[str, Sequence[str], None] = '2f47c4554ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_items', sa.Column('affected_entity_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_items', 'affected_entity_id')
    # ### end Alembic commands ###
